version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-server-new
    environment:
      MYSQL_ROOT_PASSWORD: root1user@123
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my1sql1123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: